### ISSUE TITLE
website isn't a great name, especially when forking

### ISSUE THREAD

**Issue by asoules** [hackerunion-archives/hackerunion.org#28]
This repo is called "website" which is ok in context, but after I forked it, I ended up with asoules/website, which is really unfortunate.

I realize it's a pain, but could we rename it something more specific to HU?

**Comment by johndbritton** [comment]
:+1: I'd suggest hackerunion.org

**Comment by mathisonian** [comment]
done. figured sooner is better than later on this one.

If anyone needs help getting their repo remotes working again: https://help.github.com/articles/changing-a-remote-s-url

**Comment by johndbritton** [comment]
rad :bomb:

**Comment by asoules** [comment]
Thanks Matthew!
