### ISSUE TITLE
Create a moderator role

### ISSUE THREAD

**Issue by johndbritton** [hackerunion-archives/hackerunion.org#30]
Let's have a basic moderator role that can be given to any trusted user. For now, we'll define trusted as people who have been with us at Town Halls multiple times or have been active in online discussions to the point that they are well known.

Moderators should have the ability to view the list of applications and approve and reject applicants.

Moderators should not automatically become a guide / mentor for the accepted applicant.

This will make it so that we can cut the time down on application processing and will also encourage more of our members to help with moderation because it's less of a time commitment.

**Comment by brandondiamond** [comment]
We currently have a moderator concept (see account/models.py UserProfile) -- however, it is married to the Guide concept as follows:

Guides can moderate their recruits (and access the admin queue).
Guides with "can_moderate=True' can moderate all users (and access the admin queue).
- What do we call the advisor role (referred to as Guide below)?
- What do we call the moderator role (referred to as Mod below)?
- Should moderators have global moderation ability?
- Should there be a distinction between moderators (edit anyone's posts) and access to the admin queue (respond to member tickets; accept applicants; etc)?
- What does mentorship constitute?
- What is the easiest way to convert the existing concepts into the new concept? (i.e., minimal code changes)
- Do we show the recruit view to those who have explicitly assumed mentees?
- Do we simply support a concept of "working group" which can have a certain number of members?
- How do we facilitate mentorship?
- How do we help people with certain objectives find people with certain skills/affiliations?
- How do we encourage mentorship online and offline?

Let's answer all of these questions, put together a proposal, get the community's feedback, and then break it down into github issues we can tackle together.

**Comment by johndbritton** [comment]
stale
